# Generated by Django 5.1.7 on 2025-03-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField()),
                ('contact_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('birthdate', models.CharField(max_length=10)),
                ('birthplace', models.CharField(blank=True, max_length=30, null=True)),
                ('image', models.CharField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('iban', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('account_number', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('iban', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField()),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('product', models.CharField(blank=True, max_length=30, null=True)),
                ('cost', models.CharField(blank=True, max_length=30, null=True)),
                ('contact', models.CharField(blank=True, max_length=30, null=True)),
                ('start_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
