# Generated by Django 5.1.7 on 2025-04-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthplace',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.BigIntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
