# Generated by Django 5.1.7 on 2025-04-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_birthdate_alter_account_birthplace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
