# Generated by Django 5.1.7 on 2025-04-06 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('house_number', models.IntegerField(blank=True, null=True)),
                ('addition', models.CharField(blank=True, null=True)),
                ('zip_code', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_email', models.CharField(blank=True, max_length=30, null=True)),
                ('contact_phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='contact_email',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='administration',
            old_name='contact_email',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='bank',
            old_name='contact_email',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='administration',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='email',
        ),
        migrations.RemoveField(
            model_name='family',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='contact_phone',
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AddField(
            model_name='family',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='administration',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.contact'),
        ),
    ]
