# Generated by Django 5.1.7 on 2025-04-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='room',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
