# Generated by Django 5.1.7 on 2025-04-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_room_alter_address_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
