# Generated by Django 5.1.7 on 2025-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accommodation_account_administration_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='iban',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
