# Generated by Django 5.1.7 on 2025-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_insurancecategory_insurance_policy_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administration',
            old_name='reference_number',
            new_name='reference',
        ),
        migrations.AddField(
            model_name='administration',
            name='bic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='bic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='iban',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='sepa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
