# Generated by Django 5.1.7 on 2025-04-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_reference_number_administration_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='bic',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='iban',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='sepa',
            field=models.BooleanField(default=False),
        ),
    ]
